server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.20.120:3306/vhr?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  flyway:
    locations: classpath:/db/migration